apiVersion: apps/v1
kind: Deployment
metadata:
  name: round-robin-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: round-robin-api
  template:
    metadata:
      labels:
        app: round-robin-api
    spec:
      containers:
        - name: round-robin-api
          image: round-robin-api:4
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "550m"